import { startTransition, StrictMode } from "react";
import { hydrateRoot } from "react-dom/client";
import { HydratedRouter } from "react-router/dom";

startTransition(() => {
  hydrateRoot(
    document,
    <StrictMode>
      <HydratedRouter />
    </StrictMode>,
  );
});

// Register the production service worker (generated by scripts/generate-sw.mjs).
// Guarded to PROD so dev never requests /sw.js (which React Router would 404).
if (import.meta.env.PROD && "serviceWorker" in navigator) {
  window.addEventListener("load", () => {
    void navigator.serviceWorker.register("/sw.js");
  });
}

// Keep the on-device vocabulary (IndexedDB) durable so it isn't evicted under
// storage pressure — it's the only copy now.
void navigator.storage?.persist?.();
