import { startTransition, StrictMode } from "react";
import { hydrateRoot } from "react-dom/client";
import { HydratedRouter } from "react-router/dom";

startTransition(() => {
  hydrateRoot(
    document,
    <StrictMode>
      <HydratedRouter />
    </StrictMode>,
  );
});

// Register the production service worker (generated by scripts/generate-sw.mjs).
// Guarded to PROD so dev never requests /sw.js (which React Router would 404).
if (import.meta.env.PROD && "serviceWorker" in navigator) {
  const registerSw = () => void navigator.serviceWorker.register("/sw.js");
  // `load` may already have fired by the time this deferred module runs, in
  // which case a `load` listener would never fire and the SW would never
  // register — so register immediately when the document is already loaded.
  if (document.readyState === "complete") {
    registerSw();
  } else {
    window.addEventListener("load", registerSw);
  }
}

// Keep the on-device vocabulary (IndexedDB) durable so it isn't evicted under
// storage pressure — it's the only copy now.
void navigator.storage?.persist?.();
