-- Scheduled "Ready to practice?" reminders.
--
-- THE SCHEDULE IS LIVE AND IS NOT DEFINED HERE. It is configured in the Supabase
-- dashboard (Integrations → Cron); this migration only installs the extensions
-- that job depends on. Change the schedule there, not in this file — the
-- commented block below is kept as a reference for the shape of the pg_net call
-- and is NOT what runs today.
--
-- pg_cron only runs SQL inside Postgres; to actually run the send-reminders Edge
-- Function it makes an outbound HTTP POST (via pg_net) to the function's public
-- URL, with an `Authorization: Bearer` header. The anon key satisfies the
-- gateway's verify_jwt gate, but it is NOT secret (it ships in the client
-- bundle), so it authorizes nothing on its own. The function additionally
-- requires an `x-reminders-secret` header matching the REMINDERS_SECRET secret —
-- otherwise anyone could push arbitrary text to every subscriber. Keep the
-- header on the live job in sync with the secret, or the nightly send starts
-- returning 401 silently.
--
-- Whatever fires the job, the function sends only when the hour in Europe/Berlin
-- equals REMINDER_HOUR (20) — see supabase/functions/send-reminders/index.ts. A
-- schedule expressed in UTC therefore drifts off that gate at every DST change
-- (20:00 Berlin is 18:00 UTC under CEST, 19:00 UTC under CET), and the function
-- silently sends nothing on the days it misses. Re-check the two agree whenever
-- the clocks move.
--
-- To trigger a send by hand, `force` skips the hour gate:
--   curl -X POST "$VITE_SUPABASE_URL/functions/v1/send-reminders" \
--     -H "Authorization: Bearer $VITE_SUPABASE_ANON_KEY" \
--     -H "x-reminders-secret: $REMINDERS_SECRET" -d '{"force":true}'

create extension if not exists pg_cron;
create extension if not exists pg_net;

-- Reference only — see the note above. Replace the URL and anon key with this
-- project's values if the schedule is ever moved back into SQL.
-- select cron.schedule(
--   'send-reminders-daily',
--   -- must land on 20:00 Europe/Berlin to clear REMINDER_HOUR; UTC shifts with DST
--   '0 18 * * *',
--   $$
--   select net.http_post(
--     url := 'https://<project-ref>.supabase.co/functions/v1/send-reminders',
--     headers := jsonb_build_object(
--       'Content-Type', 'application/json',
--       'Authorization', 'Bearer <anon-key>',
--       'x-reminders-secret', '<reminders-secret>'
--     ),
--     body := '{}'::jsonb
--   );
--   $$
-- );
